# Form implementation generated from reading ui file '.\sidebar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from import_perso import QtCore, QtGui, QtWidgets, QApplication, os, psutil, math
from function.function_mainmenu import (
    MyMainWindow, on_home_btn_1_toggled, toggleFullScreen, toggleSetVisible, 
    on_skins_btn_toggled,on_parametres_btn_toggled, on_packsderesources_btn_toggled,
    on_packsdeshaders_btn_toggled, on_console_btn_toggled, on_capturedecran_btn_toggled,
    on_rapportsdecrash_btn_toggled, on_rapportsdecrash_btn_toggled, on_mod_additionnel_btn_toggled,
    DrangandDropButton, on_easter_eggs_maomao, create_widget_with_label, DrangandDropButtonShader, create_widget_with_label_shader,
    handle_slider_moved, save_slider_value, read_initial_slider_value, 
    load_mods_from_url, load_mod_states, mod_checkboxes, save_mod_states, configparser

)
if not os.path.exists('config/config.ini'):
    config_fichier = configparser.ConfigParser()
    print("fichier config crée")
    config_fichier['DEFAULT'] = {'langue': 'fr'}
    # Créer une section 'Launcher' et définir les arguments JVM avec la valeur initiale de 2 Go
    config_fichier['Launcher'] = {'jvmArguments': '["-Xmx2G", "-Xms2G"]'}
                    
    # Enregistrer les modifications dans le fichier
    with open('config/config.ini', 'w') as configfile:
        config_fichier.write(configfile)

from function.gestion_langues import language_system, default_language
from function.gestion_luancher import launch_minecraft

def setupUi(account_informaton, logout):
    global main_window
    main_window = MyMainWindow()
    centralwidget = QtWidgets.QWidget(parent=main_window)
    centralwidget.setObjectName("centralwidget")
    horizontalLayout_2 = QtWidgets.QHBoxLayout(centralwidget)
    horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
    horizontalLayout_2.setSpacing(0)
    horizontalLayout_2.setObjectName("horizontalLayout_2")

    def change_language(index, comboBox_langue):
        selected_language_code = comboBox_langue.currentData()
        language_system.current_language = selected_language_code  # Met à jour la langue actuelle dans le système de langue
        language_system.load_translations(selected_language_code)  # Charge les traductions pour la nouvelle langue
        main_window.setWindowTitle(language_system.translate("MainWindow"))
        label_configuration.setText(language_system.translate("label_configuration"))
        parametres_btn.setText(language_system.translate("parametres_btn"))
        skins_btn.setText(language_system.translate("skins_btn"))
        packsderesources_btn.setText(language_system.translate("packsderesources_btn"))
        packsdeshaders_btn.setText(language_system.translate("packsdeshaders_btn"))
        console_btn.setText(language_system.translate("console_btn"))
        capturedecran_btn.setText(language_system.translate("capturedecran_btn"))
        rapportsdecrash_btn.setText(language_system.translate("rapportsdecrash_btn"))
        mod_additionnel_btn.setText(language_system.translate("mod_additionnel_btn"))
        btn_logout.setText(language_system.translate("btn_logout"))
        icon_server_conecter.setText(language_system.translate("icon_server_conecter"))
        label_nombre_de_joueurs.setText(language_system.translate("label_nombre_de_joueurs"))
        notes_mise_a_jour_btn.setText(language_system.translate("notes_mise_a_jour_btn"))
        label_spaziacraft.setText(language_system.translate("label_spaziacraft"))
        if launcher_minecraft.isEnabled():
            launcher_minecraft.setText(language_system.translate("launcher_minecraft"))
        else:
            launcher_minecraft.setText(language_system.translate("launcher_minecraft_encours"))
        version_launcher.setText(language_system.translate("version_launcher"))
        page_label_langue.setText(language_system.translate("page_label_langue"))
        page_label_reparer_jeu.setText(language_system.translate("page_label_reparer_jeu"))
        page_btn_reparer_launcher.setText(language_system.translate("page_btn_reparer_launcher"))
        label_memoire_ram.setText(language_system.translate("label_memoire_ram"))
        Label_skins.setText(language_system.translate("Label_skins"))
        page_label_packs_de_resources.setText(language_system.translate("page_label_packs_de_resources"))
        page_btn_deposer_pack.setText(language_system.translate("page_btn_deposer_pack"))
        page_label_packs_de_shaders.setText(language_system.translate("page_label_packs_de_shaders"))
        page_btn_deposer_shaders.setText(language_system.translate("page_btn_deposer_shaders"))
        Label_console.setText(language_system.translate("Label_console"))
        Label_captures_decran.setText(language_system.translate("Label_captures_decran"))
        Label_rapports_de_crash.setText(language_system.translate("Label_rapports_de_crash"))

        # -------------------------------------------------------------------------------- #
        #                      Bar lateral du Launcher                                     #
        # -------------------------------------------------------------------------------- #

    icon_only_widget = QtWidgets.QWidget(parent=centralwidget)
    icon_only_widget.setMinimumSize(QtCore.QSize(0, 0))
    icon_only_widget.setObjectName("icon_only_widget")
    verticalLayout_3 = QtWidgets.QVBoxLayout(icon_only_widget)
    verticalLayout_3.setContentsMargins(0, 0, 0, 0)
    verticalLayout_3.setSpacing(0)
    verticalLayout_3.setObjectName("verticalLayout_3")
    horizontalLayout_3 = QtWidgets.QHBoxLayout()
    horizontalLayout_3.setObjectName("horizontalLayout_3")
    logo_label_1 = QtWidgets.QLabel(parent=icon_only_widget)
    logo_label_1.setMinimumSize(QtCore.QSize(50, 50))
    logo_label_1.setMaximumSize(QtCore.QSize(50, 50))
    logo_label_1.setText("")
    logo_label_1.setPixmap(QtGui.QPixmap("asset/Design-sans-titre.png"))
    logo_label_1.setScaledContents(True)
    logo_label_1.setObjectName("logo_label_1")
    horizontalLayout_3.addWidget(logo_label_1)
    verticalLayout_3.addLayout(horizontalLayout_3)
    verticalLayout = QtWidgets.QVBoxLayout()
    verticalLayout.setSpacing(0)
    verticalLayout.setObjectName("verticalLayout")
    home_btn_1 = QtWidgets.QPushButton(parent=icon_only_widget)
    home_btn_1.setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("asset/accueil.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    icon.addPixmap(QtGui.QPixmap("asset/accueil_base.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
    home_btn_1.setIcon(icon)
    home_btn_1.setIconSize(QtCore.QSize(20, 20))
    home_btn_1.setCheckable(True)
    home_btn_1.setAutoExclusive(True)
    home_btn_1.setObjectName("home_btn_1")
    home_btn_1.clicked.connect(lambda: on_home_btn_1_toggled(stackedWidget, lateral_parametres, label_configuration))
    verticalLayout.addWidget(home_btn_1)
    dashborad_btn_1 = QtWidgets.QPushButton(parent=icon_only_widget)
    dashborad_btn_1.setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("asset/dashboard-5-32.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    icon1.addPixmap(QtGui.QPixmap("asset/dashboard-5-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
    dashborad_btn_1.setIcon(icon1)
    dashborad_btn_1.setIconSize(QtCore.QSize(20, 20))
    dashborad_btn_1.setVisible(False)
    dashborad_btn_1.setCheckable(True)
    dashborad_btn_1.setAutoExclusive(True)
    dashborad_btn_1.setObjectName("dashborad_btn_1")
    verticalLayout.addWidget(dashborad_btn_1)
    orders_btn_1 = QtWidgets.QPushButton(parent=icon_only_widget)
    orders_btn_1.setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap("asset/activity-feed-32.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    icon2.addPixmap(QtGui.QPixmap("asset/activity-feed-48.ico"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
    orders_btn_1.setIcon(icon2)
    orders_btn_1.setIconSize(QtCore.QSize(20, 20))
    orders_btn_1.setVisible(False)
    orders_btn_1.setCheckable(True)
    orders_btn_1.setAutoExclusive(True)
    orders_btn_1.setObjectName("orders_btn_1")
    verticalLayout.addWidget(orders_btn_1)
    products_btn_1 = QtWidgets.QPushButton(parent=icon_only_widget)
    products_btn_1.setText("")
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap("asset/product-32.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    icon3.addPixmap(QtGui.QPixmap("asset/product-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
    products_btn_1.setIcon(icon3)
    products_btn_1.setIconSize(QtCore.QSize(20, 20))
    products_btn_1.setVisible(False)
    products_btn_1.setCheckable(True)
    products_btn_1.setAutoExclusive(True)
    products_btn_1.setObjectName("products_btn_1")
    verticalLayout.addWidget(products_btn_1)
    customers_btn_1 = QtWidgets.QPushButton(parent=icon_only_widget)
    customers_btn_1.setText("")
    icon4 = QtGui.QIcon()
    icon4.addPixmap(QtGui.QPixmap("asset/group-32.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    icon4.addPixmap(QtGui.QPixmap("asset/group-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
    customers_btn_1.setIcon(icon4)
    customers_btn_1.setIconSize(QtCore.QSize(20, 20))
    customers_btn_1.setVisible(False)
    customers_btn_1.setCheckable(True)
    customers_btn_1.setAutoExclusive(True)
    customers_btn_1.setObjectName("customers_btn_1")
    verticalLayout.addWidget(customers_btn_1)
    verticalLayout_3.addLayout(verticalLayout)
    spacerItem = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
    verticalLayout_3.addItem(spacerItem)
    exit_btn_1 = QtWidgets.QPushButton(parent=icon_only_widget)
    exit_btn_1.setText("")
    icon5 = QtGui.QIcon()
    icon5.addPixmap(QtGui.QPixmap("asset/parametres.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    icon5.addPixmap(QtGui.QPixmap("asset/parametres_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
    exit_btn_1.setIcon(icon5)
    exit_btn_1.setIconSize(QtCore.QSize(20, 20))
    exit_btn_1.setObjectName("exit_btn_1")
    exit_btn_1.setCheckable(True)
    exit_btn_1.setAutoExclusive(True)
    verticalLayout_3.addWidget(exit_btn_1)
    horizontalLayout_2.addWidget(icon_only_widget)
    

        # -------------------------------------------------------------------------------- #
        #                      Lateral Bar Paramètres                                      #
        # -------------------------------------------------------------------------------- #

    lateral_parametres = QtWidgets.QWidget(parent=centralwidget)
    lateral_parametres.setMinimumSize(QtCore.QSize(130, 0))
    lateral_parametres.setMaximumSize(QtCore.QSize(16777215, 16777215))
    lateral_parametres.setObjectName("lateral_parametres")
    lateral_parametres.setVisible(False)
    gridLayout = QtWidgets.QGridLayout(lateral_parametres)
    gridLayout.setContentsMargins(0, 0, 0, 0)
    gridLayout.setSpacing(0)
    gridLayout.setObjectName("gridLayout")
    horizontalLayout_5 = QtWidgets.QHBoxLayout()
    horizontalLayout_5.setContentsMargins(-1, -1, -1, 10)
    horizontalLayout_5.setSpacing(0)
    horizontalLayout_5.setObjectName("horizontalLayout_5")
    spacerItem1 = QtWidgets.QSpacerItem(22, 41, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
    horizontalLayout_5.addItem(spacerItem1)
    gridLayout.addLayout(horizontalLayout_5, 0, 0, 1, 1)
    verticalLayout_4 = QtWidgets.QVBoxLayout()
    verticalLayout_4.setSpacing(0)
    verticalLayout_4.setObjectName("verticalLayout_4")
    parametres_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    parametres_btn.setCheckable(True)
    parametres_btn.setAutoExclusive(True)
    parametres_btn.setObjectName("parametres_btn")
    verticalLayout_4.addWidget(parametres_btn)
    skins_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    skins_btn.setVisible(False)
    skins_btn.setCheckable(True)
    skins_btn.setAutoExclusive(True)
    skins_btn.setObjectName("skins_btn")
    verticalLayout_4.addWidget(skins_btn)
    packsderesources_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    packsderesources_btn.setCheckable(True)
    packsderesources_btn.setAutoExclusive(True)
    packsderesources_btn.setObjectName("packsderesources_btn")
    verticalLayout_4.addWidget(packsderesources_btn)
    packsdeshaders_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    packsdeshaders_btn.setCheckable(True)
    packsdeshaders_btn.setAutoExclusive(True)
    packsdeshaders_btn.setObjectName("packsdeshaders_btn")
    verticalLayout_4.addWidget(packsdeshaders_btn)
    console_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    console_btn.setVisible(False)
    console_btn.setCheckable(True)
    console_btn.setAutoExclusive(True)
    console_btn.setObjectName("console_btn")
    verticalLayout_4.addWidget(console_btn)
    capturedecran_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    capturedecran_btn.setVisible(False)
    capturedecran_btn.setCheckable(True)
    capturedecran_btn.setAutoExclusive(True)
    capturedecran_btn.setObjectName("capturedecran_btn")
    verticalLayout_4.addWidget(capturedecran_btn)
    rapportsdecrash_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    rapportsdecrash_btn.setVisible(False)
    rapportsdecrash_btn.setCheckable(True)
    rapportsdecrash_btn.setAutoExclusive(True)
    rapportsdecrash_btn.setObjectName("rapportsdecrash_btn")
    verticalLayout_4.addWidget(rapportsdecrash_btn)
    mod_additionnel_btn = QtWidgets.QPushButton(parent=lateral_parametres)
    mod_additionnel_btn.setCheckable(True)
    mod_additionnel_btn.setAutoExclusive(True)
    mod_additionnel_btn.setObjectName("mod_additionnel_btn")
    verticalLayout_4.addWidget(mod_additionnel_btn)
    spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
    verticalLayout_4.addItem(spacerItem3)
    btn_logout = QtWidgets.QPushButton(parent=lateral_parametres)
    btn_logout.setCheckable(True)
    btn_logout.setAutoExclusive(True)
    btn_logout.setObjectName("btn_logout")
    verticalLayout_4.addWidget(btn_logout)
    gridLayout.addLayout(verticalLayout_4, 1, 0, 1, 1)
    horizontalLayout_2.addWidget(lateral_parametres)

        # -------------------------------------------------------------------------------- #
        #                     Main Menu de base                                            #
        # -------------------------------------------------------------------------------- #

    main_menu = QtWidgets.QWidget(parent=centralwidget)
    main_menu.setObjectName("main_menu")
    verticalLayout_5 = QtWidgets.QVBoxLayout(main_menu)
    verticalLayout_5.setContentsMargins(0, 0, 0, 0)
    verticalLayout_5.setSpacing(0)
    verticalLayout_5.setObjectName("verticalLayout_5")

        # -------------------------------------------------------------------------------- #
        #                      Bar de titre personnelle                                   #
        # -------------------------------------------------------------------------------- #

    header_frame = QtWidgets.QWidget(parent=main_menu)
    header_frame.setMinimumSize(QtCore.QSize(0, 40))
    header_frame.setObjectName("header_frame")
    horizontalLayout_4 = QtWidgets.QHBoxLayout(header_frame)
    horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
    horizontalLayout_4.setSpacing(0)
    horizontalLayout_4.setObjectName("horizontalLayout_4")
    label_configuration = QtWidgets.QLabel(parent=header_frame)
    label_configuration.setFixedSize(QtCore.QSize(250, 40))
    label_configuration.setText("label_configuration")
    label_configuration.setContentsMargins(10, 0, 0, 0)
    label_configuration.setVisible(False)
    spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    horizontalLayout_4.addItem(spacerItem4)
    minimize_window_button = QtWidgets.QPushButton(parent=header_frame)
    minimize_window_button.setText("")
    minimize_window_button.clicked.connect(main_window.showMinimized)
    icon6 = QtGui.QIcon()
    icon6.addPixmap(QtGui.QPixmap("asset/symbole-moins.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    minimize_window_button.setIcon(icon6)
    minimize_window_button.setObjectName("minimize_window_button")
    horizontalLayout_4.addWidget(minimize_window_button)
    restore_window_button = QtWidgets.QPushButton(parent=header_frame)
    restore_window_button.setText("")
    restore_window_button.clicked.connect(lambda: toggleFullScreen(main_window, restore_window_button))
    icon7 = QtGui.QIcon()
    icon7.addPixmap(QtGui.QPixmap("asset/augmenter-loption-de-taille.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    restore_window_button.setIcon(icon7)
    restore_window_button.setObjectName("restore_window_button")
    horizontalLayout_4.addWidget(restore_window_button)
    close_window_button = QtWidgets.QPushButton(parent=header_frame)
    close_window_button.setText("")
    close_window_button.clicked.connect(QApplication.quit)
    icon8 = QtGui.QIcon()
    icon8.addPixmap(QtGui.QPixmap("asset/supprimer-le-symbole.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
    close_window_button.setIcon(icon8)
    close_window_button.setObjectName("close_window_button")
    horizontalLayout_4.addWidget(close_window_button)
    verticalLayout_5.addWidget(header_frame)
    stackedWidget = QtWidgets.QStackedWidget(parent=main_menu)
    stackedWidget.setObjectName("stackedWidget")

    exit_btn_1.clicked.connect(lambda: toggleSetVisible(label_configuration, lateral_parametres, stackedWidget, home_btn_1))
    skins_btn.clicked.connect(lambda: on_skins_btn_toggled(stackedWidget))
    parametres_btn.clicked.connect(lambda: on_parametres_btn_toggled(stackedWidget))
    packsderesources_btn.clicked.connect(lambda: on_packsderesources_btn_toggled(stackedWidget))
    packsdeshaders_btn.clicked.connect(lambda: on_packsdeshaders_btn_toggled(stackedWidget))
    console_btn.clicked.connect(lambda: on_console_btn_toggled(stackedWidget))
    capturedecran_btn.clicked.connect(lambda: on_capturedecran_btn_toggled(stackedWidget))
    rapportsdecrash_btn.clicked.connect(lambda: on_rapportsdecrash_btn_toggled(stackedWidget))
    mod_additionnel_btn.clicked.connect(lambda: on_mod_additionnel_btn_toggled(stackedWidget))
    btn_logout.clicked.connect(lambda: logout())
        # -------------------------------------------------------------------------------- #
        #                      Page de base du luancher                                    #
        # -------------------------------------------------------------------------------- #

    page_home = QtWidgets.QWidget()
    page_home.setObjectName("page_home")
    gridLayout_2 = QtWidgets.QGridLayout(page_home)
    gridLayout_2.setObjectName("gridLayout_2")
    widget = QtWidgets.QWidget(parent=page_home)
    widget.setFixedSize(QtCore.QSize(350, 200))
    widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
    widget.setObjectName("widget")
    verticalLayout_7 = QtWidgets.QVBoxLayout(widget)
    verticalLayout_7.setContentsMargins(0, 0, 0, 0)
    verticalLayout_7.setSpacing(0)
    verticalLayout_7.setObjectName("verticalLayout_7")
    horizontalLayout_6 = QtWidgets.QHBoxLayout()
    horizontalLayout_6.setSpacing(0)
    horizontalLayout_6.setObjectName("horizontalLayout_6")
    icon_server_conecter = QtWidgets.QLabel(parent=widget)
    icon_server_conecter.setMaximumSize(QtCore.QSize(20, 50))
    icon_server_conecter.setObjectName("icon_server_conecter")
    icon_server_conecter.setVisible(False)
    horizontalLayout_6.addWidget(icon_server_conecter)
    label_nombre_de_joueurs = QtWidgets.QLabel(parent=widget)
    label_nombre_de_joueurs.setMaximumSize(QtCore.QSize(16777215, 50))
    label_nombre_de_joueurs.setObjectName("label_nombre_de_joueurs")
    label_nombre_de_joueurs.setVisible(False)
    horizontalLayout_6.addWidget(label_nombre_de_joueurs)
    notes_mise_a_jour_btn = QtWidgets.QPushButton(parent=widget)
    notes_mise_a_jour_btn.setObjectName("notes_mise_a_jour_btn")
    notes_mise_a_jour_btn.setVisible(False)
    horizontalLayout_6.addWidget(notes_mise_a_jour_btn)
    verticalLayout_7.addLayout(horizontalLayout_6)
    verticalLayout_6 = QtWidgets.QVBoxLayout()
    verticalLayout_6.setContentsMargins(0, 0, 0, 0)  # Ajoute une marge de 10 pixels en bas
    verticalLayout_6.setSpacing(0)
    verticalLayout_6.setObjectName("verticalLayout_6")
    label_spaziacraft = QtWidgets.QLabel(parent=widget)
    label_spaziacraft.setMaximumSize(QtCore.QSize(16777215, 100))
    label_spaziacraft.setObjectName("label_spaziacraft")
    verticalLayout_6.addWidget(label_spaziacraft)
    # Select version novisible
    select_version = QtWidgets.QComboBox(parent=widget)
    select_version.setVisible(False)
    select_version.addItem("Stable")
    select_version.addItem("Beta")
    select_version.setObjectName("select_version")
    verticalLayout_6.addWidget(select_version)
    launcher_minecraft = QtWidgets.QPushButton(parent=widget)
    launcher_minecraft.setFixedSize(QtCore.QSize(16777215, 20))
    launcher_minecraft.setMaximumSize(QtCore.QSize(16777215, 16777215))
    launcher_minecraft.setCheckable(True)
    launcher_minecraft.setAutoExclusive(True)
    launcher_minecraft.setObjectName("launcher_minecraft")
    verticalLayout_6.addWidget(launcher_minecraft)
    label_progrssBar = QtWidgets.QLabel(parent=widget)
    label_progrssBar.setMaximumSize(QtCore.QSize(16777215, 50))
    label_progrssBar.setObjectName("label_progrssBar")
    label_progrssBar.setVisible(False)
    verticalLayout_6.addWidget(label_progrssBar)
    progressBar = QtWidgets.QProgressBar(parent=widget)
    progressBar.setProperty("value", 24)
    progressBar.setObjectName("progressBar")
    progressBar.setVisible(False)
    verticalLayout_6.addWidget(progressBar)
    version_launcher = QtWidgets.QLabel(parent=widget)
    version_launcher.setMaximumSize(QtCore.QSize(16777215, 50))
    version_launcher.setObjectName("version_launcher")
    verticalLayout_6.addWidget(version_launcher)
    verticalLayout_7.addLayout(verticalLayout_6)
    gridLayout_2.addWidget(widget, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignBottom)
    stackedWidget.addWidget(page_home)
    launcher_minecraft.clicked.connect(lambda: launch_minecraft(account_informaton, progressBar, launcher_minecraft, comboBox_langue, label_progrssBar))
              
        # -------------------------------------------------------------------------------- #
        #                page de paramètre (RAM,Réparer le luancher)                       #
        # -------------------------------------------------------------------------------- #

    page_parametres = QtWidgets.QWidget()
    page_parametres.setObjectName("page_parametres")
    gridLayout_3 = QtWidgets.QGridLayout(page_parametres)
    gridLayout_3.setSpacing(0)
    gridLayout_3.setObjectName("gridLayout_3")
    verticalLayout_2 = QtWidgets.QVBoxLayout()
    gridLayout_3.setContentsMargins(10, 20, 10, 0)
    verticalLayout_2.setSpacing(0)
    verticalLayout_2.setObjectName("verticalLayout_2")

    page_label_langue = QtWidgets.QLabel(parent=page_parametres)
    page_label_langue.setObjectName("page_label_langue")
    page_label_langue.setMaximumSize(QtCore.QSize(16777215, 20))
    verticalLayout_2.addWidget(page_label_langue)
    comboBox_langue = QtWidgets.QComboBox(parent=page_parametres)
    comboBox_langue.setMaximumSize(QtCore.QSize(200, 16777215))
    comboBox_langue.setObjectName("comboBox_langue")
    comboBox_langue.addItem("French", "fr")
    comboBox_langue.addItem("English", "en")
    # Set the default language
    default_language_index = comboBox_langue.findData(default_language)
    if default_language_index != -1:
        comboBox_langue.setCurrentIndex(default_language_index)
    comboBox_langue.currentIndexChanged.connect(lambda index: change_language(index, comboBox_langue))
    verticalLayout_2.addWidget(comboBox_langue)
    verticalLayout_2.setContentsMargins(0, 0, 0, 20)

    page_label_reparer_jeu = QtWidgets.QLabel(parent=page_parametres)
    page_label_reparer_jeu.setMaximumSize(QtCore.QSize(16777215, 16777215))
    page_label_reparer_jeu.setObjectName("page_label_reparer_jeu")
    verticalLayout_2.addWidget(page_label_reparer_jeu)
    page_btn_reparer_launcher = QtWidgets.QPushButton(parent=page_parametres)
    page_btn_reparer_launcher.setObjectName("page_btn_reparer_launcher")
    verticalLayout_2.addWidget(page_btn_reparer_launcher)

    # Paramétres de la RAM
    label_memoire_ram = QtWidgets.QLabel(parent=page_parametres)
    label_memoire_ram.setMaximumSize(QtCore.QSize(16777215, 20))
    label_memoire_ram.setObjectName("label_memoire_ram")
    verticalLayout_2.addWidget(label_memoire_ram)
    horizontalLayout_slider = QtWidgets.QHBoxLayout()
    label_slider = QtWidgets.QLabel(parent=page_parametres)
    label_slider.setObjectName("label_slider")
    label_slider.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)  # Aligner le texte au centre

    # Obtenez la quantité totale de RAM disponible en Go
    total_ram_gb = psutil.virtual_memory().total / (1024 ** 3)  # Convertir en Go
    rounded_total_ram_gb = math.ceil(total_ram_gb)  # Arrondir à l'entier supérieur 
    horizontalLayout_slider.addWidget(label_slider)
    horizontalSlider = QtWidgets.QSlider(parent=page_parametres)
    horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
    horizontalSlider.setObjectName("horizontalSlider")

    # Lire la valeur initiale du curseur à partir du fichier config.ini
    initial_slider_value = read_initial_slider_value()
    label_slider.setText(f"{initial_slider_value} Go")
    horizontalSlider.setValue(initial_slider_value)

    horizontalSlider.setPageStep(2)
    horizontalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
    horizontalSlider.setRange(2, int(rounded_total_ram_gb))
    horizontalSlider.setTickInterval(2)
    horizontalSlider.valueChanged.connect(lambda value: label_slider.setText(f"{value} Go"))
    horizontalLayout_slider.addWidget(horizontalSlider)
    verticalLayout_2.addLayout(horizontalLayout_slider) 
    # Connecter le gestionnaire d'événements à l'événement sliderMoved
    horizontalSlider.sliderMoved.connect(lambda value: handle_slider_moved(value, horizontalSlider))
    horizontalSlider.sliderReleased.connect(lambda : save_slider_value(horizontalSlider))

    spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
    verticalLayout_2.addItem(spacerItem4)
    gridLayout_3.addLayout(verticalLayout_2, 7, 0, 1, 1)
    stackedWidget.addWidget(page_parametres)

        # -------------------------------------------------------------------------------- #
        #                      page Pour les skins des joueur                              #
        # -------------------------------------------------------------------------------- #

    page_skins = QtWidgets.QWidget()
    page_skins.setObjectName("page_skins")
    gridLayout_4 = QtWidgets.QGridLayout(page_skins)
    gridLayout_4.setObjectName("gridLayout_4")
    Label_skins = QtWidgets.QLabel(parent=page_skins)
    font = QtGui.QFont()
    font.setPointSize(20)
    Label_skins.setFont(font)
    Label_skins.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
    Label_skins.setObjectName("Label_skins")
    gridLayout_4.addWidget(Label_skins, 0, 0, 1, 1)
    stackedWidget.addWidget(page_skins)

        # -------------------------------------------------------------------------------- #
        #                      page pour le packs de resources                             #
        # -------------------------------------------------------------------------------- #
    
    page_packs_de_resources = QtWidgets.QWidget()
    page_packs_de_resources.setObjectName("page_packs_de_resources")
    gridLayout_5 = QtWidgets.QGridLayout(page_packs_de_resources)
    gridLayout_5.setObjectName("gridLayout_5")
    verticalLayout_8 = QtWidgets.QVBoxLayout()
    verticalLayout_8.setObjectName("verticalLayout_8")
    page_label_packs_de_resources = QtWidgets.QLabel(parent=page_packs_de_resources)
    page_label_packs_de_resources.setObjectName("page_label_packs_de_resources")
    verticalLayout_8.addWidget(page_label_packs_de_resources)

    page_btn_deposer_pack = DrangandDropButton(parent=page_packs_de_resources)
    page_btn_deposer_pack.setFixedSize(QtCore.QSize(16777215, 50))
    page_btn_deposer_pack.setObjectName("page_btn_deposer_pack")


    verticalLayout_8.addWidget(page_btn_deposer_pack)
    scrollArea_pack_de_resource = QtWidgets.QScrollArea(parent=page_packs_de_resources)
    scrollArea_pack_de_resource.setWidgetResizable(True)
    scrollArea_pack_de_resource.setObjectName("scrollArea_pack_de_resource")
    scrollAreaWidgetContents_2 = QtWidgets.QWidget()
    scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 731, 490))
    scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
    verticalLayout_9 = QtWidgets.QVBoxLayout(scrollAreaWidgetContents_2)
    verticalLayout_9.setContentsMargins(0, 0, 0, 0)
    verticalLayout_9.setSpacing(0)
    verticalLayout_9.setObjectName("verticalLayout_9")

    global filenames
    filenames = []
    global refresh_file_list
    def refresh_file_list(minecraft_directory):
        print("Refresh packs de resources")
        global new_filenames
        new_filenames = set()  # Utilisation d'un ensemble pour éviter les duplications
        dir_path = os.path.join(minecraft_directory, "resourcepacks")  # Utilisez os.path.join pour construire le chemin d'accès

        # Vérifier si le dossier "resourcepacks" existe, sinon le créer
        if not os.path.exists(dir_path):
            os.makedirs(dir_path)

        for path in os.listdir(dir_path):
            if os.path.isfile(os.path.join(dir_path, path)):
                filename, _ = os.path.splitext(path)
                new_filenames.add(filename)

        # Comparez les nouveaux fichiers avec ceux déjà présents pour éviter les duplications
        new_files = new_filenames - set(filenames)
        if new_files:
            filenames.extend(new_files)
            for filename in new_files:
                create_widget_with_label(filename, scrollAreaWidgetContents_2, verticalLayout_9)


    scrollArea_pack_de_resource.setWidget(scrollAreaWidgetContents_2)
    verticalLayout_8.addWidget(scrollArea_pack_de_resource)
    gridLayout_5.addLayout(verticalLayout_8, 0, 0, 1, 1)
    stackedWidget.addWidget(page_packs_de_resources)

        # -------------------------------------------------------------------------------- #
        #                          page pour le shaders packes                             #
        # -------------------------------------------------------------------------------- #

    page_packs_de_shaders = QtWidgets.QWidget()
    page_packs_de_shaders.setObjectName("page_packs_de_shaders")
    gridLayout_6 = QtWidgets.QGridLayout(page_packs_de_shaders)
    gridLayout_6.setObjectName("gridLayout_6")
    verticalLayout_10 = QtWidgets.QVBoxLayout()
    verticalLayout_10.setObjectName("verticalLayout_10")
    page_label_packs_de_shaders = QtWidgets.QLabel(parent=page_packs_de_shaders)
    page_label_packs_de_shaders.setObjectName("page_label_packs_de_shaders")
    verticalLayout_10.addWidget(page_label_packs_de_shaders)


    page_btn_deposer_shaders = DrangandDropButtonShader(parent=page_packs_de_shaders)
    page_btn_deposer_shaders.setFixedSize(QtCore.QSize(16777215, 50))
    page_btn_deposer_shaders.setObjectName("page_btn_deposer_shaders")

    verticalLayout_10.addWidget(page_btn_deposer_shaders)
    scrollArea_shader_packs = QtWidgets.QScrollArea(parent=page_packs_de_shaders)
    scrollArea_shader_packs.setWidgetResizable(True)
    scrollArea_shader_packs.setObjectName("scrollArea_shader_packs")
    scrollAreaWidgetContents_3 = QtWidgets.QWidget()
    scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 731, 490))
    scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
    verticalLayout_11 = QtWidgets.QVBoxLayout(scrollAreaWidgetContents_3)
    verticalLayout_11.setContentsMargins(0, 0, 0, 0)
    verticalLayout_11.setSpacing(0)
    verticalLayout_11.setObjectName("verticalLayout_11")

    global filenames_shader
    filenames_shader = []
    global refresh_file_list_shaders
    def refresh_file_list_shaders(minecraft_directory):
        print("Refresh packs de Shader")
        global new_filenames_shader
        new_filenames_shader = set()  # Utilisation d'un ensemble pour éviter les duplications
        dir_path = os.path.join(minecraft_directory, "shaderpacks")  # Utilisez os.path.join pour construire le chemin d'accès

                # Vérifier si le dossier "shaderpacks" existe, sinon le créer
        if not os.path.exists(dir_path):
            os.makedirs(dir_path)

        for path in os.listdir(dir_path):
            if os.path.isfile(os.path.join(dir_path, path)):
                filename, _ = os.path.splitext(path)
                new_filenames_shader.add(filename)

        # Comparez les nouveaux fichiers avec ceux déjà présents pour éviter les duplications
        new_files = new_filenames_shader - set(filenames_shader)
        if new_files:
            filenames_shader.extend(new_files)
            for filename in new_files:
                create_widget_with_label_shader(filename, scrollAreaWidgetContents_3, verticalLayout_11)

    scrollArea_shader_packs.setWidget(scrollAreaWidgetContents_3)
    verticalLayout_10.addWidget(scrollArea_shader_packs)
    gridLayout_6.addLayout(verticalLayout_10, 0, 0, 1, 1)
    stackedWidget.addWidget(page_packs_de_shaders)

        # -------------------------------------------------------------------------------- #
        #                 page pour afficher ou non la console                             #
        # -------------------------------------------------------------------------------- #

    page_console = QtWidgets.QWidget()
    page_console.setObjectName("page_console")
    gridLayout_7 = QtWidgets.QGridLayout(page_console)
    gridLayout_7.setObjectName("gridLayout_7")
    Label_console = QtWidgets.QLabel(parent=page_console)
    font = QtGui.QFont()
    font.setPointSize(20)
    Label_console.setFont(font)
    Label_console.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
    Label_console.setObjectName("Label_console")
    gridLayout_7.addWidget(Label_console, 0, 0, 1, 1)
    stackedWidget.addWidget(page_console)

        # -------------------------------------------------------------------------------- #
        #                       page pour les captures d'écrant                            #
        # -------------------------------------------------------------------------------- #

    page_captures_decran = QtWidgets.QWidget()
    page_captures_decran.setObjectName("page_captures_decran")
    gridLayout_8 = QtWidgets.QGridLayout(page_captures_decran)
    gridLayout_8.setObjectName("gridLayout_8")
    Label_captures_decran = QtWidgets.QLabel(parent=page_captures_decran)
    font = QtGui.QFont()
    font.setPointSize(20)
    Label_captures_decran.setFont(font)
    Label_captures_decran.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
    Label_captures_decran.setObjectName("Label_captures_decran")
    gridLayout_8.addWidget(Label_captures_decran, 0, 0, 1, 1)
    stackedWidget.addWidget(page_captures_decran)

        # -------------------------------------------------------------------------------- #
        #                      page pour le rapports de crash                              #
        # -------------------------------------------------------------------------------- #

    page_rapports_de_crash = QtWidgets.QWidget()
    page_rapports_de_crash.setObjectName("page_rapports_de_crash")
    gridLayout_9 = QtWidgets.QGridLayout(page_rapports_de_crash)
    gridLayout_9.setObjectName("gridLayout_9")
    Label_rapports_de_crash = QtWidgets.QLabel(parent=page_rapports_de_crash)
    font = QtGui.QFont()
    font.setPointSize(20)
    Label_rapports_de_crash.setFont(font)
    Label_rapports_de_crash.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
    Label_rapports_de_crash.setObjectName("Label_rapports_de_crash")
    gridLayout_9.addWidget(Label_rapports_de_crash, 0, 0, 1, 1)
    stackedWidget.addWidget(page_rapports_de_crash)


        # -------------------------------------------------------------------------------- #
        #                      page mods client en plus                                    #
        # -------------------------------------------------------------------------------- #

    page_mod_additionnel_btn = QtWidgets.QWidget()
    page_mod_additionnel_btn.setObjectName("page_mod_additionnel_btn")
    gridLayout_10 = QtWidgets.QGridLayout(page_mod_additionnel_btn)
    gridLayout_10.setObjectName("gridLayout_10")
    verticalLayout_13 = QtWidgets.QVBoxLayout()
    verticalLayout_13.setObjectName("verticalLayout_13")
    page_label_packs_de_shaders_2 = QtWidgets.QLabel(parent=page_mod_additionnel_btn)
    page_label_packs_de_shaders_2.setObjectName("page_label_packs_de_shaders_2")
    verticalLayout_13.addWidget(page_label_packs_de_shaders_2)
    scrollArea_shader_packs_2 = QtWidgets.QScrollArea(parent=page_mod_additionnel_btn)
    scrollArea_shader_packs_2.setWidgetResizable(True)
    scrollArea_shader_packs_2.setObjectName("scrollArea_shader_packs_2")
    scrollAreaWidgetContents_4 = QtWidgets.QWidget()
    scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 731, 490))
    scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
    verticalLayout_14 = QtWidgets.QVBoxLayout(scrollAreaWidgetContents_4)
    verticalLayout_14.setContentsMargins(0, 0, 0, 0)
    verticalLayout_14.setSpacing(0)
    verticalLayout_14.setObjectName("verticalLayout_14")
    global mod_additionnel_def
    def mod_additionnel_def():
        # Charger les mods depuis l'URL
        mods_list = load_mods_from_url()
        # Charger les états des QCheckBox
        saved_states = load_mod_states()

        # Parcourir la liste des mods et vérifier si le mod est additionnel
        for mod in mods_list:
            if mod["is_additional"]:
                print("passe3")
                widget_4 = QtWidgets.QWidget(parent=scrollAreaWidgetContents_4)
                widget_4.setObjectName("widget_4")
                gridLayout_13 = QtWidgets.QGridLayout(widget_4)
                gridLayout_13.setObjectName("gridLayout_13")

                page_label_name_mod_additionnel = QtWidgets.QLabel(parent=widget_4)
                page_label_name_mod_additionnel.setObjectName("page_label_name_mod_additionnel")
                page_label_name_mod_additionnel.setText(mod["name"])
                gridLayout_13.addWidget(page_label_name_mod_additionnel, 0, 1, 1, 1)

                checkBox = QtWidgets.QCheckBox(parent=widget_4)
                checkBox.setText("")
                checkBox.setObjectName("checkBox")
                gridLayout_13.addWidget(checkBox, 0, 0, 1, 1)

                verticalLayout_14.addWidget(widget_4)

                # Restaurer l'état du checkbox si sauvegardé
                if mod["name"] in saved_states:
                    checkBox.setChecked(saved_states[mod["name"]])

                # Connecter le signal stateChanged à la fonction save_mod_states
                checkBox.stateChanged.connect(save_mod_states)

                # Ajouter la QCheckBox au dictionnaire avec le nom du mod comme clé
                mod_checkboxes[mod["name"]] = checkBox

    scrollArea_shader_packs_2.setWidget(scrollAreaWidgetContents_4)
    verticalLayout_13.addWidget(scrollArea_shader_packs_2)
    gridLayout_10.addLayout(verticalLayout_13, 0, 0, 1, 1)
    stackedWidget.addWidget(page_mod_additionnel_btn)
    verticalLayout_5.addWidget(stackedWidget)
    horizontalLayout_2.addWidget(main_menu)
    main_window.setCentralWidget(centralwidget)

    # -------------------------------------------------------------------------------- #
    #                      varible start main menu                                     #
    # -------------------------------------------------------------------------------- #

    logo_label_1.mousePressEvent = lambda event: on_easter_eggs_maomao(event, logo_label_1)
    stackedWidget.setCurrentIndex(0)
    home_btn_1.setChecked(True)
    change_language(comboBox_langue.currentIndex(), comboBox_langue)
    main_window.show()
    return main_window

def refresh_file_lists(minecraft_directory):
    global refresh_file_list
    global refresh_file_list_shaders
    global mod_additionnel_def
    refresh_file_list(minecraft_directory)
    refresh_file_list_shaders(minecraft_directory)
    mod_additionnel_def()
    save_mod_states()